name: Jekyll Bootstrap Blog
description: A blog theme for Jekyll using Twitter Bootstrap
author: Andrew Shell

disqus_shortname: test1geekity

navigation:
- text: Home
  url: /
- text: About
  url: /about.html
- text: Layouts
  url: /layouts.html
  children:
  - text: Default
    url: /layout/default.html

paginate: 10

# Scheme and Hostname for your website without trailing slash
# (ex: https://andrewshell.github.com)
url: http://www.jekyll-bootstrap-blog

# Folder part of the path to get to your website without trailing slash
# (ex: /projectname)
baseurl:

auto: true
safe: true
server: true